version: "3"

services:
  db:
    image: postgres
    environment: 
      POSTGRES_DB: project_db
      POSTGRES_USER: projectUser 
      POSTGRES_PASSWORD: root
    ports: 
      - 5433:5432
    restart: unless-stopped

  ui: 
    build: ./frontend/
    command: npm start
    ports:
     - 3003:3000
    volumes: 
     - ./src:/usr/app/src
     - ./public:/usr/app/public

         
  api:
    build: ./backend/
    command: sh -c "npm run migrate && npm start"
    ports:
     - 3334:3334
    volumes: 
     - ./src:/usr/app/api
    restart: unless-stopped